exports._id = function (env) {
    return {
        "Site_Name": {"value": "Rocket Chat Compentio Admin Console"},
        "Site_Url": {"value": `${env.DOMAIN_URL}/rocketchat`},
        "Organization_Type": {"value": "nonprofit"},
        "Organization_Name": {"value": "Compentio"},
        "Industry": {"value": "helpCenter"},
        "Size": {"value": "0"},
        "Country": {"value": "Poland"},
        "Website": {"value": ""},
        "Server_Type": {"value": "privateTeam"},
        "FileUpload_ProtectFiles": {"value": false},
        "FileUpload_Enabled_Direct": {"value": true},
        "Allow_Marketing_Emails": {"value": false},
        "Register_Server": {"value": false},
        "Organization_Email": {"value": ""},
        "Allow_Invalid_SelfSigned_Certs": {"value": true},
        "Iframe_Restrict_Access": {"value": true},
        "Iframe_Integration_send_enable": {"value": true},
        "Iframe_Integration_receive_enable": {"value": true},
        "Message_AllowUnrecognizedSlashCommand": {"value": true},
        "Message_Read_Receipt_Enabled": {"value": true},
        "Message_Read_Receipt_Store_Users": {"value": true},
        "Markdown_Headers": {"value": true},
        "Katex_Enabled": {"value": true},
        "Katex_Parenthesis_Syntax": {"value": true},
        "Notifications_Always_Notify_Mobile": {"value": true},
        "Accounts_iframe_enabled": {"value": true},
        "Accounts_iframe_url": {"value": `${env.DOMAIN_URL}/auth-service/rocketchat/login`},
        "Accounts_Iframe_api_method": {"value": "POST"},
        "Accounts_Iframe_api_url": {"value": `${env.DOMAIN_URL}/auth-service/rocketchat/auth`},
        "First_Channel_After_Login": {"value": "general"},
        "UI_Allow_room_names_with_special_chars": {"value": true},
        "Layout_Home_Title": {"value": "Home"},
        "Layout_Home_Body": {"value": "Welcome to Compentio chat that can be embedded and authorized your app"},
        "SMTP_Protocol": {"value": `${env.ROCKETCHAT_SMTP_HOST}`},
        "SMTP_Host": {"value": `${env.ROCKETCHAT_SMTP_HOST}`},
        "SMTP_Port": {"value": `${env.ROCKETCHAT_SMTP_PORT}`},
        "SMTP_Username": {"value": `${env.ROCKETCHAT_SMTP_USERNAME}`},
        "SMTP_Password": {"value": `${env.ROCKETCHAT_SMTP_PASSWORD}`},
        "From_Email": {"value": `${env.ROCKETCHAT_FROM_EMAIL}`},
        "Message_AllowDeleting": {"value": true},
        "Message_ShowEditedStatus": {"value": true},
        "Message_ShowDeletedStatus": {"value": true},
        "E2E_Enable": {"value": true}
    }
}